In [1]:
import numpy as np
np_array = np.array([[1,2,3],[4,2,5]])
type(np_array)


numpy.ndarray

In [2]:
print(np_array)
print(np_array.ndim)
print(np_array.shape)
print(np_array.size)
print(np_array.dtype)

[[1 2 3]
 [4 2 5]]
2
(2, 3)
6
int32


In [3]:
a = np.array([[1,2,4],[5,8,7]],dtype = 'float')
print(a)
c = np.zeros((3,4))
c

[[1. 2. 4.]
 [5. 8. 7.]]


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [4]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [6]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [7]:
#create a sequence of integers from 0 to 30 with steps of 5
print(np.arange(0,30,5))

[ 0  5 10 15 20 25]


In [8]:
#create a sequence of 10 values in range 0 to 5
print(np.linspace(0,5,10))

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [14]:
arr = np_array.reshape((3,2))
arr

array([[1, 2],
       [3, 4],
       [2, 5]])

In [16]:
arr = arr+1
arr

array([[2, 3],
       [4, 5],
       [3, 6]])

In [17]:
arr = arr*3
arr

array([[ 6,  9],
       [12, 15],
       [ 9, 18]])

In [18]:
arr.max()

18

In [19]:
arr.max(axis=1)

array([ 9, 15, 18])

In [20]:
arr.max(axis=0)

array([12, 18])

In [21]:
arr.sum()

69

In [22]:
#dot product
arr.dot(np_array)

array([[ 42,  30,  63],
       [ 72,  54, 111],
       [ 81,  54, 117]])

In [25]:
#multiply
arr*np_array.reshape(3,2)

array([[ 6, 18],
       [36, 60],
       [18, 90]])

In [26]:
np.sort(arr,axis = 1)

array([[ 6,  9],
       [12, 15],
       [ 9, 18]])

In [32]:
a= np.array([[1,2],[3,4]])
b= np.array([[5,6],[7,8]])

print("Hstack\n",np.vstack((a,b)))
print("Vstack\n",np.hstack((a,b)))

c= [5,6]
print("Column Stack\n",np.column_stack((a,c)))
print("Concatenate to 2nd axis\n",np.concatenate((a,b),1))

Hstack
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Vstack
 [[1 2 5 6]
 [3 4 7 8]]
Column Stack
 [[1 2 5]
 [3 4 6]]
Concatenate to 2nd axis
 [[1 2 5 6]
 [3 4 7 8]]


In [35]:
a = np.array([[1,3,5,7],[2,4,6,8]])
print("Horizontal Split\n",np.hsplit(a,2))
print("Vertical Split\n",np.vsplit(a,2))

Horizontal Split
 [array([[1, 3],
       [2, 4]]), array([[5, 7],
       [6, 8]])]
Vertical Split
 [array([[1, 3, 5, 7]]), array([[2, 4, 6, 8]])]


In [39]:
b=np.array([1,5,4,2,3])
print(np.median(c))
print(np.mean(c))


5.5
5.5


In [40]:
w = np.array([1,1,1,1,1])
print(np.average(b,weights=w))

3.0


In [41]:
u = np.mean(c)
myStd = np.sqrt(np.mean(abs(c-u)**2))
myStd


0.5

In [42]:
np.var(b)

2.0

In [44]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
np.random.seed(1)
np.random.shuffle(a)
a

array([6, 5, 1, 0, 2, 4, 9, 7, 8, 3])

In [48]:
np.random.randint(5,10,3)

array([9, 6, 7])

In [52]:
ele = np.random.choice([1,2,3,4,5,6,7])
ele

3