# Numpy Exercise

#### 1. Import the numpy package under the name as np  

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration 

In [4]:
print(np.version.version)

1.19.2


#### 3. Create a null vector of size 10

In [6]:
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array

In [7]:
len() function

10

## 5.  How to get the documentation of the numpy add function from the command line? 

In [8]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6.  Create a null vector of size 10 but the fifth value which is 1

In [11]:
y = np.zeros(10)
y[4] = 1
y

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7.  Create a vector with values ranging from 10 to 49

In [13]:
r = np.arange(10,50)
r

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8.  Reverse a vector (first element becomes last)

In [15]:
r[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8

In [20]:
arr = np.arange(0,9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\]

In [21]:
arr.nonzero()

(array([0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

#### 11. Create a 3x3 identity matrix

In [23]:
i = np.identity(3)
i

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values

In [26]:
x = np.random.random((3,3,3))
x

array([[[0.00466941, 0.9443077 , 0.27098212],
        [0.16875812, 0.52804025, 0.56199119],
        [0.93806214, 0.02131441, 0.3486971 ]],

       [[0.90957478, 0.99743251, 0.37156285],
        [0.61506783, 0.76070673, 0.54565913],
        [0.38604827, 0.94551757, 0.90978517]],

       [[0.70213972, 0.8870627 , 0.93030352],
        [0.08129984, 0.5541389 , 0.66443394],
        [0.29409233, 0.68432237, 0.04519788]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [30]:
x = np.random.random((10,10))
print(x)
print(x.min())
print(x.max())

[[0.27613519 0.43354218 0.52245421 0.17253136 0.97482551 0.01570856
  0.70466772 0.03050219 0.55106412 0.66131572]
 [0.45867311 0.31193196 0.27170869 0.5097767  0.52633886 0.83482791
  0.84853274 0.17624611 0.03337407 0.3724935 ]
 [0.30159566 0.82649707 0.79228937 0.74417778 0.65260511 0.59187567
  0.87926683 0.08476716 0.67260311 0.35112864]
 [0.67101226 0.55852417 0.03860134 0.54185604 0.77698939 0.58415668
  0.96361122 0.80110263 0.60095327 0.07022072]
 [0.17468467 0.21440511 0.02423882 0.66873024 0.69960431 0.54382249
  0.14334602 0.68803861 0.79605215 0.20444385]
 [0.74213625 0.65528373 0.27926589 0.35155022 0.69960825 0.98367317
  0.12573039 0.0404431  0.47051529 0.43164337]
 [0.76719851 0.37109989 0.82928423 0.08142364 0.42632212 0.15995453
  0.17740877 0.12298802 0.04547953 0.84822651]
 [0.92063204 0.64605456 0.49488975 0.10796507 0.88633214 0.16110714
  0.52191617 0.80141233 0.14263151 0.14711718]
 [0.35709335 0.251853   0.85193436 0.09900142 0.71114278 0.12837346
  0.96628397

#### 14. Create a random vector of size 30 and find the mean value

In [35]:
mean = np.random.random((30))
mean.mean()

0.5230892803073375

#### 15. Create a 2d array with 1 on the border and 0 inside

In [41]:
border = np.ones((8,8))
border[1:-1,1:-1]=0
border

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array?

In [43]:
border = np.pad(border, pad_width=1, mode='constant', constant_values=0)
border

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression?

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [32]:
False

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [50]:
arr = np.random.random((5,5))
j=1;k=1
for i in range(1,5):
    arr[i,j-1] = k  
    j=j+1;k+=1
print(arr)

[[0.45811734 0.58103563 0.64827732 0.58757534 0.09471898]
 [1.         0.49224475 0.99214588 0.27048134 0.36358787]
 [0.22374942 2.         0.5587441  0.00560534 0.38524822]
 [0.06071455 0.75579067 3.         0.26657227 0.81227308]
 [0.82450246 0.41976711 0.54213389 4.         0.09445663]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [44]:

x = np.zeros((8,8))
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


# 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [51]:
np.unravel_index(100, (6,7,8))

(1, 5, 4)